- name: check for registry
  local_action:
    shell helm status registry
  register: registry_status
  ignore_errors: true
  changed_when: false

- name: add incubator registry
  local_action:
    shell helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
    
- name: install registry through helm
  local_action:
    shell helm install --name registry incubator/docker-registry
  when: registry_status.rc != 0

- name: create registry ingress yaml
  local_action:
    template src=registry-ingress.yaml dest=./yamls/registry-ingress.yaml

- name: create registry ingress
  local_action:
    shell kubectl apply -f ./yamls/registry-ingress.yaml

- name: wait for registry to become ready
  wait_for:
    host: "{{ minikube_ip.stdout }}"
    port: 30400
    timeout: 1200

- name: add some annotations so the ingress can handle large files (registry)
  local_action:
    shell kubectl annotate cm -n kube-system nginx-load-balancer-conf {{ item }}
  with_items:
    - "ingress.kubernetes.io/proxy-body-size=201m"
    - "nginx.org/client-max-body-size=202m"
  ignore_errors: true

- name: scale nginx ingress down and up
  local_action:
    shell kubectl scale rc nginx-ingress-controller -n kube-system --replicas=0 && sleep 5 && kubectl scale rc nginx-ingress-controller -n kube-system --replicas=1
  when: minikube_result.stdout_lines[0].find("Running") == -1

 
