#!/usr/bin/env ansible-playbook
- hosts: localhost
  become: false
  gather_facts: False
  environment:
    PYTHONPATH: /usr/local/lib/python2.7/site-packages
  roles:
    - preflight
    - minikube
    - helm
    - registry
    - gitlab
    - jenkins
    - prometheus
    - clair