- name: check for jenkins
  local_action:
    shell helm status jenkins
  register: jenkins_status
  ignore_errors: true
  changed_when: false

- name: create jenkins values file
  local_action:
    template src=jenkins-values.yaml dest=./yamls/jenkins-values.yaml

- name: install jenkins through helm
  local_action:
    shell helm install stable/jenkins --values=./yamls/jenkins-values.yaml --name=jenkins
  when: jenkins_status.rc != 0

- name: get jenkins nodeport
  local_action:
    shell kubectl get svc jenkins-jenkins -o jsonpath="{.spec.ports[0].nodePort}"
  changed_when: false
  register: jenkins_nodeport

- name: wait for jenkins to become ready (depending on your connection, it can take a while)
  wait_for:
    host: "{{ minikube_ip.stdout }}"
    port: "{{ jenkins_nodeport.stdout }}"
    timeout: 1200

- name: open docker.sock for jenkins
  local_action:
    shell ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /Users/mansmatulewicz/.minikube/machines/minikube/id_rsa docker@{{ minikube_ip.stdout }}  sudo chmod 666 /var/run/docker.sock
  changed_when: false

- name: create jenkins ingress yaml
  local_action:
    template src=jenkins-ingress.yaml dest=./yamls/jenkins-ingress.yaml

- name: create jenkins ingress
  local_action:
    shell kubectl apply -f ./yamls/jenkins-ingress.yaml