apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: registry
  namespace: default
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.org/client-max-body-size: "203m"
    ingress.kubernetes.io/proxy-body-size: 204m
spec:
  rules:
  - host: registry.{{ domainname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: docker-registry-registry
          servicePort: 4000