# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Master:
  Name: jenkins-master
  Image: "jenkinsci/jenkins"
  ImageTag: {{ jenkins_version }}
  ImagePullPolicy: "Always"
  Component: "jenkins-master"
  UseSecurity: true
  AdminUser: admin
  AdminPassword: adminpass
  Cpu: "200m"
  Memory: "512Mi"
# Set min/max heap here if needed with:
# JavaOpts: "-Xms512m -Xmx512m"
# JenkinsOpts: ""
# JenkinsUriPrefix: "/jenkins"
  ServicePort: 8080
# For minikube, set this to NodePort, elsewhere use LoadBalancer
# Use ClusterIP if your setup includes ingress controller
  ServiceType: NodePort
# Master Service annotations
  ServiceAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/probe: "true"
      prometheus.io/path: "/prometheus"
      prometheus.io/port: "8080"
       #service.beta.kubernetes.io/prometheus.io/scrape: true
       #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
# Used to create Ingress record (should used with ServiceType: ClusterIP)
# HostName: jenkins.cluster.local
# NodePort: <to set explicitly, choose port between 30000-32767
  ContainerPort: 8080
  SlaveListenerPort: 50000
  LoadBalancerSourceRanges:
  - 0.0.0.0/0
# Optionally assign a known public LB IP
# LoadBalancerIP: 1.2.3.4
# Optionally configure a JMX port
# requires additional JavaOpts, ie
# JavaOpts: >
#   -Dcom.sun.management.jmxremote.port=4000
#   -Dcom.sun.management.jmxremote.authenticate=false
#   -Dcom.sun.management.jmxremote.ssl=false
# JMXPort: 4000
# List of plugins to be install during Jenkins master start
  InstallPlugins:
      - branch-api:2.0.11
      - kubernetes:0.11
      - workflow-aggregator:2.5
      - workflow-job:2.14.1
      - credentials-binding:1.13
      - git:3.6.0
      - docker-commons
      - greenballs
      - blueocean
      - prometheus
# Used to approve a list of groovy functions in pipelines used the script-security plugin. Can be viewed under /scriptApproval
  ScriptApproval:
    - "method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods toInteger java.lang.Number"
  #   - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
  #   - "new groovy.json.JsonSlurperClassic"
# List of groovy init scripts to be executed during Jenkins master start
  InitScripts:
  - |
      import java.util.Collections;

      import jenkins.model.*

      import org.jenkinsci.plugins.docker.commons.*
      import org.jenkinsci.plugins.docker.commons.tools.*

      import hudson.plugins.git.*
      import hudson.plugins.git.extensions.GitSCMExtension;
      import hudson.tools.ToolLocationNodeProperty;
      import hudson.tools.ToolProperty;


      import com.cloudbees.plugins.credentials.impl.*;
      import com.cloudbees.plugins.credentials.*;
      import com.cloudbees.plugins.credentials.domains.*;

      import org.csanchez.jenkins.plugins.kubernetes.volumes.*;
      import org.csanchez.jenkins.plugins.kubernetes.*


      def inst = Jenkins.getInstance()

      def desc = inst.getDescriptor("org.jenkinsci.plugins.docker.commons.tools.DockerTool")
      def dinst = new DockerTool(
        "current",
        "/",
        Collections.<ToolProperty<?>>emptyList()
      )
      desc.setInstallations(dinst)

      desc.save()

      k = inst.getCloud("kubernetes")

      def p = new PodTemplate()
      p.setName('buildslave')
      p.setLabel('clair')
      p.setRemoteFs('/home/jenkins')


      c = new ContainerTemplate("buildslave", "registry.example.com:80/slave", "","")
      c.setArgs("\${computer.jnlpmac} \${computer.name}")

      ContainerEnvVar te_url = new ContainerEnvVar("JENKINS_URL", "http://jenkins.example.com");
      c.setEnvVars(Arrays.asList(te_url));

      PodVolume pvsock = new HostPathVolume("/var/run/docker.sock", "/var/run/docker.sock");
      PodVolume pvbin = new HostPathVolume("/bin/docker", "/bin/docker");

      p.getContainers().add(c);
      p.setVolumes(Arrays.asList(pvsock, pvbin));

      k.addTemplate(p)

      Credentials c = new UsernamePasswordCredentialsImpl(CredentialsScope.GLOBAL, "demo", "description:", "root", "{{ gitlab_root_password }}")
      SystemCredentialsProvider.getInstance().getStore().addCredentials(Domain.global(), c)


      def scm = new GitSCM("http://gitlab-gitlab-ce.default/Demo/demorepo.git")
      scm =  new GitSCM( scm.createRepoList("http://gitlab-gitlab-ce.default/Demo/demorepo.git", "demo"), 
                         Collections.singletonList(new BranchSpec("*/master")),
                         false, Collections.<SubmoduleConfig>emptyList(),
                         null, null,
                         Collections.<GitSCMExtension>emptyList());

      def flowDefinition = new org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition(scm, "Jenkinsfile")
      def job = new org.jenkinsci.plugins.workflow.job.WorkflowJob(inst, "Demo Job")
      job.definition = flowDefinition
      inst.reload()

#  - |
  #  print 'adding global pipeline libraries, register properties, bootstrap jobs...'
  CustomConfigMap: false
# Node labels and tolerations for pod assignment
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
  NodeSelector: {}
  Tolerations: {}

  Ingress:
    Annotations:
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    TLS:
      # - secretName: jenkins.cluster.local
      #   hosts:
      #     - jenkins.cluster.local

Agent:
  Enabled: true
  Image: jenkinsci/jnlp-slave
  ImageTag: 2.62
  Component: "jenkins-slave"
  Privileged: true
  Cpu: "200m"
  Memory: "512Mi"
  # You may want to change this to true while testing a new image
  AlwaysPullImage: false
  # You can define the volumes that you want to mount for this container
  # Allowed types are: ConfigMap, EmptyDir, HostPath, Nfs, Pod, Secret
  # Configure the attributes as they appear in the corresponding Java class for that type
  # https://github.com/jenkinsci/kubernetes-plugin/tree/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes
  volumes:
    - type: HostPath
      hostPath: "/var/run/docker.sock"
      mountPath: "/var/run/docker.sock"
    - type: HostPath
      hostPath: "/bin/docker"
      mountPath: "/bin/docker"
  # - type: Secret
  #   secretName: mysecret
  #   mountPath: /var/myapp/mysecret
  NodeSelector: {}
  # Key Value selectors. Ex:
  # jenkins-agent: v1

Persistence:
  Enabled: true
  ## A manually managed Persistent Volume and Claim
  ## Requires Persistence.Enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # ExistingClaim:

  ## jenkins data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # StorageClass: "-"

  AccessMode: ReadWriteOnce
  Size: 8Gi
  volumes:
#  - name: nothing
#    emptyDir: {}
  mounts:
#  - mountPath: /var/nothing
#    name: nothing
#    readOnly: true

NetworkPolicy:
  # Enable creation of NetworkPolicy resources.
  Enabled: true
  # For Kubernetes v1.4, v1.5 and v1.6, use 'extensions/v1beta1'
  # For Kubernetes v1.7, use 'networking.k8s.io/v1'
  ApiVersion: networking.k8s.io/v1

## Install Default RBAC roles and bindings
rbac:
  install: true
  serviceAccountName: jenkins-jenkins
  # RBAC api version (currently either v1beta1 or v1alpha1)
  apiVersion: v1beta1
  # Cluster role reference
  roleRef: cluster-admin