apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: keycloak.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak
          servicePort: 8080