apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    # chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    app: keycloak
  type: ClusterIP
  ports:
  - name: keycloak
    port: 8080
    targetPort: 8080
    protocol: TCP