apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: keycloak
  labels:
    # chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    app: keycloak-postgres
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP