server:
  ingress:
    enabled: true
    hosts:
      - prometheus.{{ domainname }}

alertmanager:
  ingress:
    enabled: true
    hosts:
      - alerts.{{ domainname }}

nodeExporter:
  enabled: true

rbac:
  create: true